### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by staxmanade** [w1zeman1p/topic-vote#1]
should include

```
jspm_packages/
node_modules/
```

**Comment by staxmanade** [comment]
You can reference this to remove the existing folders

http://staxmanade.com/2015/02/how-to-remove-files-in-git-that-should-have-been-ignored/

**Comment by cjavdev** [comment]
:) i always forget. I wish `npm init` would create a .gitignore and ignore its self when created. same with jspm.
