### ISSUE TITLE
Return the System.import promise

### ISSUE THREAD

**Issue by staxmanade** [w1zeman1p/topic-vote#2]
Here add a `return` statement to return the promise

https://github.com/w1zeman1p/topic-vote/blob/master/index.html#L10

**Comment by cjavdev** [comment]
thanks :+1:

**Comment by ninthward** [comment]
I thought I closed it? was it still open?

**Comment by cjavdev** [comment]
This was a different one

On Thursday, February 18, 2016, campbell mckeogh notifications@github.com
wrote:

> I thought I closed it? was it still open?
> 
> On Thu, Feb 18, 2016 at 7:48 AM, CJ Avilla <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Closed #2 https://github.com/w1zeman1p/topic-vote/issues/2.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/w1zeman1p/topic-vote/issues/2#event-555268050.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w1zeman1p/topic-vote/issues/2#issuecomment-186066236.

## 
- CJ

**Comment by ninthward** [comment]
hahah sorry man
